This is workout for Muliple variables in Linear Regression
price = m1 * area + m2 * bedrooms + m3 * age + b
m1, m2 , m3 ---> coeffients
area bedrooms age ---> independent variables 
price  ----> Dependent variable

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n


In [10]:
home_price = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\homeprices")
home_price

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
# We are using math function in order to use floor function as we need to round the bedrooms
import math
median_bedrooms = math.floor(home_price.bedrooms.median())
median_bedrooms
#home_price.fillna(median_bedrooms)   this will replace NaN on all the columns
#home_price.bedrooms.fillna(median_bedrooms)


4

In [12]:
# Below column will replace null values only in bedrooms column
home_price.bedrooms = home_price.bedrooms.fillna(median_bedrooms)
home_price


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(home_price[['area','bedrooms','age']],home_price.price)

In [ ]:
reg.coef_
#reg.predict(2500,3,16)

In [ ]:
reg.intercept_

In [ ]:
reg.predict([[2400,3,40]])

In [ ]:
reg.predict([[3000,3,40]])

%%%%%%%%%%%%%%%%%%%%%%%%%%  Workout  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In [94]:
hiring_read = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\hiring")
hiring_read

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
pip install word2number

In [95]:

hiring_read.experience = hiring_read.experience.fillna("zero")
hiring_read.experience = hiring_read.experience.apply(w2n.word_to_num)
hiring_read

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [96]:
import math
median_test_score = math.floor(hiring_read['test_score(out of 10)'].mean())
#median_test_score = math.floor(hiring_read['test_score(out of 10)'].mean())

hiring_read['test_score(out of 10)'] = hiring_read['test_score(out of 10)'].fillna(median_test_score)
hiring_read

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [100]:
reg = linear_model.LinearRegression()
#reg = linear_model.LinearRegression()

In [102]:
reg.fit(hiring_read[['experience','test_score(out of 10)','interview_score(out of 10)']],hiring_read[['salary($)']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [104]:
reg.predict([[2,9,6]])

array([[53713.86677124]])

In [105]:
reg.predict([[12,10,10]])

array([[93747.79628651]])

# Second time

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [12]:

df2 = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\homeprices")
df2

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
import math
mis_bed = df2.bedrooms.median()
#df2.fillna('bedrooms').median()
mis_bed

4.0

In [19]:
df2.bedrooms = df2.bedrooms.fillna(mis_bed)

In [20]:
df2

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [24]:
reg = linear_model.LinearRegression()

In [25]:
reg.fit(df2[['area','bedrooms','age']],df2.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
reg.predict([[1500,2,12]])

array([397413.81003089])

In [37]:
df3 = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\hiring")
df3

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [38]:
med = df3['test_score(out of 10)'].median()
df3['test_score(out of 10)'] = df3['test_score(out of 10)'].fillna(med)
df3

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [39]:
pip install word2number


Note: you may need to restart the kernel to use updated packages.


In [40]:
df3['experience'] = df3['experience'].fillna('zero')

In [41]:
df3

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [42]:
from word2number import w2n
df3['experience'] = df3.experience.apply(w2n.word_to_num)

In [45]:
df3
reg = linear_model.LinearRegression()
reg.fit(df3[['experience','test_score(out of 10)','interview_score(out of 10)']],df3[['salary($)']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [47]:
reg.predict([[2,9,6]])

array([[53205.96797671]])

In [48]:
reg.predict([[12,10,10]])

array([[92002.18340611]])

# Pickle   model

In [49]:
import pickle

In [51]:
with open(r"C:\Users\Lenovo\Desktop\Data_Science\tgt\pickle_model",'wb') as f:
    pickle.dump(reg,f)

In [52]:
with open(r"C:\Users\Lenovo\Desktop\Data_Science\tgt\pickle_model",'rb') as f:
    mp = pickle.load(f)

In [53]:
mp.predict([[2,9,6]])

array([[53205.96797671]])

###########  Passing file #################

In [55]:
areaa = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\Model_file_ip.txt")
a = reg.predict(areaa)
areaa['salary($)'] = a

In [56]:
areaa

experience  test_score(out of 10)  interview_score(out of 10)     salary($)
0           4                      3                           5  45552.401747
1          12                      8                           9  86105.531295
2           0                      2                           4  30249.636099

# JOBLIB

In [57]:
from sklearn.externals import joblib

C:\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [58]:
joblib.dump(reg,r"C:\Users\Lenovo\Desktop\Data_Science\tgt\pickle_model_joblib")

['C:\\Users\\Lenovo\\Desktop\\Data_Science\\tgt\\pickle_model_joblib']

In [60]:
mj = joblib.load(r"C:\Users\Lenovo\Desktop\Data_Science\tgt\pickle_model_joblib")

In [61]:
mj.predict([[2,9,6]])

array([[53205.96797671]])