Save Model Using Joblib And Pickle . Here we are using the same model which we used in 01_LG_Single_variable

We can save using 
   1 . Pickle
   2 . sklearn joblib
   
If the model contains more number of numpy arrays then joblib provides better results and solution

In [ ]:
import pandas as pd
import numpy as np
#import matplotlib.plot as plt
import matplotlib.pyplot as plt
from sklearn import linear_model
df = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\can")
%matplotlib inline
plt.xlabel("YEAR")
plt.ylabel("per_capita_income")
plt.title("Canada_per_cap_in")
plt.bar(df.year,df.per_capita_income)
#reg = linear_model.linearRegression()


In [21]:
reg = linear_model.LinearRegression()
reg.fit(df[['year']],df.per_capita_income)
reg.predict([[5000]])

array([2510114.61825809])

# Writing/Saving to model using Pickle 

In [ ]:
import pickle

In [33]:
with open(r'C:\Users\Lenovo\Desktop\Data_Science\Code\model_pickle2','wb') as f:
    pickle.dump(reg,f)

# Reading from model using pickle

In [34]:
with open(r'C:\Users\Lenovo\Desktop\Data_Science\Code\model_pickle2','rb') as f:
    model = pickle.load(f)

In [35]:
model.predict([[4000]])

array([1681649.54303538])

# Writing/Saving to model using Joblib

In [38]:
#from sklearn.externals import joblib
from sklearn.externals import joblib



In [40]:
joblib.dump(reg,r'C:\Users\Lenovo\Desktop\Data_Science\Code\model_joblib')

['C:\\Users\\Lenovo\\Desktop\\Data_Science\\Code\\model_joblib']

In [42]:
laa = joblib.load(r'C:\Users\Lenovo\Desktop\Data_Science\Code\model_joblib')

In [45]:
laa.predict([[4000]])

array([1681649.54303538])