# 04_Dummy Variables & One Hot Encoding

Machine learning are good in handling Numeric data better than String data
There are two types of categorical variables

Nominal : Here there is no ordering between this numbers 
          eg : Gender,color etc ...

odinal : Here there is  ordering between this numbers 
         eg : Education (10th, inter, bachelors, masters etc ...  ///// high , medium and low

# Dummy Variables method

In [ ]:
import pandas as pd



In [97]:
readd = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\homeprices_new")
readd

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [122]:
dummy = pd.get_dummies(readd.town)

In [99]:
merged = pd.concat([readd,dummy],axis='columns')

In [100]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [101]:
final = merged.drop(['town','west windsor'],axis='columns')

In [102]:
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [103]:
x = final.drop('price',axis='columns')
x

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [ ]:
x

In [104]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [105]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.fit(x,y)

In [106]:
model.predict(x) 

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [107]:
model.predict([[3000,0,1]])


array([616155.12792948])

In [108]:
reg = linear_model.LinearRegression()

In [109]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [110]:
model.predict(x) 

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [111]:
model.predict([[3000,0,1]])

array([616155.12792948])

In [112]:
model.score(x,y)

0.9573929037221873

# One Hot Encoding

In [114]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [117]:
dfle =  readd
readd.town = le.fit_transform(dfle.town)   //////  fit_transform will give numbering to strings
readd

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [119]:
x = dfle[['town','area']].values   ////  we are using values as we need two dimensional arrays
x

town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [121]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

# Second time

# Get Dummies

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [37]:

new_df = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\homeprices_new")
new_df.head(3)

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000

In [6]:
newdf1 = pd.get_dummies(new_df.town)

In [97]:
mergedd = pd.concat([new_df,newdf1],axis='columns')
#mergedd = pd.concat([new_df,newdf1],axis=1)   ###### above one the current one are same
mergedd.head(2)

town  area   price  monroe township  robinsville  west windsor
0     0  2600  550000                1            0             0
1     0  3000  565000                1            0             0

In [39]:
final1 = mergedd.drop(['town','monroe township'],axis=1)
final1.head(2)

area   price  robinsville  west windsor
0  2600  550000            0             0
1  3000  565000            0             0

In [47]:
reg = linear_model.LinearRegression()
reg.fit(final1[['area','robinsville','west windsor']],final1.price)

 ########################  OR #########################

#from sklearn.linear_model import LinearRegression
#model = LinearRegression()
#model.fit(final1[['area','robinsville','west windsor']],final1.price)
#model.predict([[3000,0,0]])

#********************  OR ************************* #

#x = final1.drop('price',axis=1)
#y = final1.price

#model.fit(x,y)
#model.predict([[3000,0,0]])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
x.head(3)

area  robinsville  west windsor
0  2600            0             0
1  3000            0             0
2  3200            0             0

In [49]:
reg.predict([[3000,0,0]])

array([590468.71640507])

In [50]:
reg.predict([[3000,1,0]])

array([616155.12792948])

In [51]:
reg.predict([[3000,0,1]])

array([630482.69189422])

In [52]:
reg.score(x,y)

0.9573929037221871

# One hot encoding

In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [72]:
dfle = new_df

dfle['town'] = le.fit_transform(dfle.town)
dfle.head(2)

town  area   price
0     0  2600  550000
1     0  3000  565000

In [73]:
#####  converting into arrau
x1 = dfle[['town','area']].values
x1



array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [74]:
y = dfle.price
y.head(2)

0    550000
1    565000
Name: price, dtype: int64

In [75]:
##### create a dummy variable column using one hot encoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
###  hear we are saying that dummy variable should be created on first column
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')  
x1 = ct.fit_transform(x1)  
x1


array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [76]:
###  Here we are removing first column as part of dummy vriable trap
x1 = x1[:,1:]
x1

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [77]:
model.fit(x1,y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [78]:
model.predict([[0,1,3400]])

array([681241.6684584])

# Excerise

# Get Dummies

In [84]:
car = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\carprices1")
car.head(3)
                  

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5

In [87]:
dummy = pd.get_dummies(car[['Car Model']])

In [98]:
new_dum = pd.concat([car,dummy],axis=1)
op = new_dum.drop(['Car Model','Car Model_Audi A5'],axis=1)
op.head(2)

Mileage  Sell Price($)  Age(yrs)  Car Model_BMW X5  \
0    69000          18000         6                 1   
1    35000          34000         3                 1   

   Car Model_Mercedez Benz C class  
0                                0  
1                                0

In [100]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(op[['Mileage','Age(yrs)','Car Model_BMW X5','Car Model_Mercedez Benz C class']],op['Sell Price($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [102]:
#Price of mercedez benz that is 4 yr old with mileage 45000
model1.predict([[45000,4,0,1]])


array([36991.31721061])

# OneHotEncoding

In [125]:
car.head(3)

Car Model  Mileage  Sell Price($)  Age(yrs)
0          1    69000          18000         6
1          1    35000          34000         3
2          1    57000          26100         5

In [126]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
car['Car Model'] = le.fit_transform(car['Car Model'])
car.head(2)


Car Model  Mileage  Sell Price($)  Age(yrs)
0          1    69000          18000         6
1          1    35000          34000         3

In [127]:
from sklearn.preprocessing import OneHotEncoder
oh1 = OneHotEncoder()
x4 = car[['Car Model','Sell Price($)','Age(yrs)']].values
y4 = car['Sell Price($)'].values


In [128]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
###  hear we are saying that dummy variable should be created on first column
ct = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder = 'passthrough')  
x4 = ct.fit_transform(x4)  
x4


array([[0.00e+00, 1.00e+00, 0.00e+00, 1.80e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.40e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.61e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.15e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 2.94e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.93e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.20e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.00e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.10e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.30e+04, 5.00e+00]])

In [129]:
x4 = x4[:,1:]

In [131]:
model1.fit(x4,y4)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [132]:
model.score(x4,y4)

1.0

In [133]:
model1.predict([[45000,4,0,1]])


array([4.5672707e-08])