# 09_Decision Tree

Entropy : It is measure of randomness or unpredicability in the dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\salaries")
df.head(3)

In [ ]:
input1 = df.drop('salary_more_then_100k',axis='columns')
input1.head(2)

In [ ]:
output1 = df.salary_more_then_100k

In [ ]:
from sklearn.preprocessing import LabelEncoder
#lbe_company = LabelEncoder()
#lbe_job = LabelEncoder()
#lbe_degree = LabelEncoder()
lbe = LabelEncoder()


In [ ]:
input1['lbe_company1'] = lbe.fit_transform(input1['company'])

In [ ]:
input1.head

In [ ]:
input1['job1'] = lbe.fit_transform(input1['job'])

In [ ]:
input1.head

In [ ]:
input1['degree_n'] = lbe.fit_transform(input1['degree'])

In [ ]:
input1

In [ ]:
final = input1.drop(['company','job','degree'],axis = 'columns')

In [132]:
final

lbe_company1  job1  degree_n
0              2     2         0
1              2     2         1
2              2     0         0
3              2     0         1
4              2     1         0
5              2     1         1
6              0     2         1
7              0     1         0
8              0     0         0
9              0     0         1
10             1     2         0
11             1     2         1
12             1     0         0
13             1     0         1
14             1     1         0
15             1     1         1

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()


In [ ]:
model.fit(final,output1)

In [ ]:
model.predict([[2,0,1]])

In [ ]:
model.predict([[1,1,1]])

In [ ]:
model.score(final,output1)

# Excerise

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [122]:
inputs = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\titanic.csv")
inputs.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [123]:
inputs = df_read.drop(['PassengerId','Survived','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250

In [124]:
inputs.Age.head(6)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
Name: Age, dtype: float64

In [133]:
df_output = df_read.Survived
df_output.head

<bound method NDFrame.head of 0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64>

In [125]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

#df_input.Age = df_input.Age.fillna(df_input.Age.mean())



In [126]:
df_input.head(6)

Pclass     Sex        Age     Fare
0       3    male  22.000000   7.2500
1       1  female  38.000000  71.2833
2       3  female  26.000000   7.9250
3       1  female  35.000000  53.1000
4       3    male  35.000000   8.0500
5       3    male  29.699118   8.4583

In [128]:
df_input.Sex = df_input.Sex.map({'male':1,'female':2})

In [129]:
df_input

Pclass  Sex        Age     Fare
0         3    1  22.000000   7.2500
1         1    2  38.000000  71.2833
2         3    2  26.000000   7.9250
3         1    2  35.000000  53.1000
4         3    1  35.000000   8.0500
..      ...  ...        ...      ...
886       2    1  27.000000  13.0000
887       1    2  19.000000  30.0000
888       3    2  29.699118  23.4500
889       1    1  26.000000  30.0000
890       3    1  32.000000   7.7500

[891 rows x 4 columns]

In [130]:
from sklearn import tree

In [131]:
from sklearn.model_selection import train_test_split


In [135]:
X_train, X_test, y_train, y_test = train_test_split(df_input,df_output,test_size=0.2)

In [136]:
from sklearn import tree

In [137]:
model = tree.DecisionTreeClassifier()


In [138]:
model.fit(X_train,y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [139]:
model.score(X_train,y_train)

0.9817415730337079

In [140]:
model.predict([[3,2,35,56]])

array([1], dtype=int64)

In [141]:
model.predict([[3,2,12,1520]])

array([0], dtype=int64)

# df['flower_name'] =df.target.apply(lambda x: iris.target_names[x])
df.head()

# Second Time

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sal = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\salaries")
sal.head(3)

company               job     degree  salary_more_then_100k
0  google   sales executive  bachelors                      0
1  google   sales executive    masters                      0
2  google  business manager  bachelors                      1

In [3]:
ip = sal.drop(['salary_more_then_100k'],axis=1)

In [4]:
ip.head(3)

company               job     degree
0  google   sales executive  bachelors
1  google   sales executive    masters
2  google  business manager  bachelors

In [5]:
tg = sal.salary_more_then_100k

In [6]:
tg.head(2)

0    0
1    0
Name: salary_more_then_100k, dtype: int64

## using LabelEncoder

In [18]:
from sklearn.preprocessing import LabelEncoder
le_com = LabelEncoder()
le_job = LabelEncoder()
le_deg = LabelEncoder()

In [19]:
ip['Company_n'] = le_com.fit_transform(ip['company'])
ip['job_n'] = le_com.fit_transform(ip['job'])
ip['degree_n'] = le_com.fit_transform(ip['degree'])

In [20]:
ip.head(2)

company              job     degree  Company_n  job_n  degree_n
0  google  sales executive  bachelors          2      2         0
1  google  sales executive    masters          2      2         1

In [25]:
ip.drop(['company','job','degree'],axis=1,inplace=True)

In [26]:
ip

Company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [27]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(ip,tg)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [31]:
model.score(ip,tg)

1.0

In [32]:
model.predict([[2,0,0]])

array([1], dtype=int64)

In [33]:
model.predict([[2,2,0]])

array([0], dtype=int64)

# Excerise

In [48]:
tit = pd.read_csv(r"C:\Users\Lenovo\Desktop\Data_Science\src\titanic.csv")
tit.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [49]:
tit.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [50]:
tit['Age'].mean()

29.69911764705882

In [51]:
tit['Age'] = tit.Age.fillna(tit.Age.mean())

#inputs.Age = inputs.Age.fillna(inputs.Age.mean())


In [52]:
tit.isnull().sum()
tit.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [53]:
tit.Sex = tit.Sex.map({'male': 1, 'female': 2})

tit.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    2  38.0      1      0   
2                             Heikkinen, Miss. Laina    2  26.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S

In [57]:
ip = tit[['Pclass','Sex','Age','Fare']]
ip.head(2)

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833

In [59]:
op = tit.Survived
op.head(2)

0    0
1    1
Name: Survived, dtype: int64

In [61]:
from sklearn.model_selection import train_test_split


In [62]:
X_train, X_test, y_train, y_test = train_test_split(ip,op,test_size=0.2)

In [64]:
len(X_train)
len(X_test)

179

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()


In [65]:
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [66]:
model.predict([[3,2,50,7]])

array([0], dtype=int64)

In [67]:
model.predict([[1,2,50,70]])

array([1], dtype=int64)

In [69]:
model.predict([[1,1,20,7]])

array([0], dtype=int64)

In [70]:
model.score(X_test,y_test)


0.770949720670391