# 12 - K Fold Cross Validation
cross validation tells which models perfoms better

In [19]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
digits = load_digits()

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [26]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_train,y_train)

0.9984089101034208

In [28]:
svn = SVC()
svn.fit(X_train,y_train)
svn.score(X_train,y_train)

0.9984089101034208

In [30]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9574074074074074

## Kfold method

In [36]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [37]:
# This will randomly split the data based on n_splits we defined

for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


## Function to know score of any model#######

In [38]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [42]:
get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test)

0.95

In [43]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9740740740740741

In [44]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9611111111111111

## StratifiedKFold is better as it will divide each classification category in uniform way

In [46]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [67]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                    digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
    

In [68]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [69]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [70]:
scores_rf

[0.9265442404006677, 0.9515859766277128, 0.9248747913188647]

## above can be replaced with below code

In [73]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [75]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [77]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93055556, 0.91944444, 0.96100279, 0.96657382, 0.9275766 ])

In [78]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)

array([0.92777778, 0.90833333, 0.95543175, 0.9637883 , 0.91922006])

## Parameter tunning